# ######## Jekyll Site Settings ##########
theme: jekyll-theme-profile
title: Jekyll Theme Profile
description: Theme built with jekyll-theme-profile
# image: /assets/img/social-preview.png
# repository: athackst/jekyll-theme-profile

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      image: /assets/img/default.png # The default image used for social and posts.
      layout: "post"
      permalink: :year/:month/:day/:title:output_ext
      toc: true
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
      image: /assets/img/default.png # The default image used for social and posts.

# ########### Theme settings ###############
# The style of the website
style: appbar # One of "stacked", "sidebar", "topbar", "appbar"
# The user/project avatar.  If not set the avatar of the project owner will be used.
# user_image: /assets/img/user-image.jpg
# The themes to use for dark and light
dark_theme: dark # One of dark, dark_dimmed, dark_colorblind, dark_high_contrast, dark_tritanopia
light_theme: light # One of light, light_colorblind, light_high_contrast, light_tritanopia

repo_info: true # Show the information for the source of this project
user_metadata: true # Show the metadata associated with the user
profile_link: true # Show a link to the github profile for the user

##########################
# # Social media settings
# icon_color: "#959da5" # The color of the social media icons on the site
# social_media: # Your social media accounts
#   behance: your_username
#   dribbble: your_username
#   docker: your_username
#   facebook: your_username
#   github: your_username
#   hackerrank: your_username
#   instagram: your_username
#   keybase: your_username
#   linkedin: your_username
#   mail: email@address
#   mastodon: your_username
#   medium: your_username
#   stackoverflow: your_user_id
#   telegram: your_username
#   threads: your_username
#   tiktok: your_username
#   twitter: your_username
#   unsplash: your_username
#   vk: your_username
#   vscode: your_username
#   youtube: your_username
#   x: your_username

####################
# Navigation links
# nav:
#   - name: Posts
#     url: /blog
#   - name: Categories
#     url: /category/

####################
# List of links for link cards
# links:
#   - name: All blog posts
#     url: /blog
#     thumbnail: /assets/img/blog-post-icon.png
#   - name: Browse by category
#     url: /category/
#     thumbnail: /assets/img/category-icon.png

###################
# Repositories to show on home page
repositories:
  sort_by: stars #pushed or stars
  limit: 24
  exclude:
    archived: true
    forks: true
    repositories:
      # - list of respositories to exclude

########################
# Post settings
related_by: "tags or categories"

# ########### Plugin settings ###############
plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-toc
  - jemoji

####################
# jekyll-paginate settings
# Include `gem jekyll-paginate` in your gemfile
# paginate: 6 # The number of posts to show per page of pagination of blog posts
# paginate_path: "/blog/page:num"
# ###################
# jekyll-tagging settings
# Include `gem jekyll-tagging` in your gemfile
# tag_page_layout: tags
# tag_page_dir: tags
# ####################
# jekyll-category-pages settings
# Include `gem jekyll-category-pages` in your gemfile
# category_path: category
# category_layout: category_layout.html
######################

# ########### Build settings ###############
exclude:
  - spec
  - demo
